.TH "deprecated" 3 "20 Oct 2006" "Modbus Slave C++ Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List
 
.IP "\fBMember \fBstartupServer\fP(int slaveAddr, const char *const portName, long baudRate, int dataBits, int stopBits, int parity) \fP" 1c
This function is deprecated. The preferred way of assigning a slave address is using the default constructor and configuring data table and slave address using addDataTable method. 
.PP
.PP
 
.IP "\fBMember \fBstartupServer\fP(int slaveAddr, const char *const portName, long baudRate) \fP" 1c
This function is deprecated. The preferred way of assigning a slave address is using the default constructor and configuring data table and slave address using addDataTable method. 
.PP
.PP
 
.IP "\fBMember \fBMbusAsciiSlaveProtocol\fP(\fBMbusDataTableInterface\fP *dataTablePtr) \fP" 1c
This function is deprecated. The preferred way of assigning a dataTable is using the default constructor and configuring data table and slave address using addDataTable method. 
.PP
.PP
 
.IP "\fBMember \fBMbusRtuSlaveProtocol\fP(\fBMbusDataTableInterface\fP *dataTablePtr) \fP" 1c
This function is deprecated. The preferred way of assigning a dataTable is using the default constructor and configuring data table and slave address using addDataTable method. 
.PP
.PP
 
.IP "\fBMember \fBstartupServer\fP(int slaveAddr, const char *const portName, long baudRate, int dataBits, int stopBits, int parity) \fP" 1c
This function is deprecated. The preferred way of assigning a slave address is using the default constructor and configuring data table and slave address using addDataTable method. 
.PP
.PP
 
.IP "\fBMember \fBMbusTcpSlaveProtocol\fP(\fBMbusDataTableInterface\fP *dataTablePtr) \fP" 1c
This function is deprecated. The preferred way of assigning a dataTable is using the default constructor and configuring data table and slave address using addDataTable method. 
.PP
.PP
 
.IP "\fBMember \fBstartupServer\fP(int slaveAddr) \fP" 1c
This function is deprecated. The preferred way of assigning a slave address is using the default constructor and configuring data table and slave address using addDataTable method. 
.PP
.PP
 
.IP "\fBMember \fBstartupServer\fP(int slaveAddr, const char *const hostName) \fP" 1c
This function is deprecated. The preferred way of assigning a slave address is using the default constructor and configuring data table and slave address using addDataTable method. 
.PP

