.TH "design" 3 "26 May 2004" "Modbus Protocol Library Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
design \- Design Background
\fIFieldTalk\fP is based on a programming language neutral but object oriented design model.
.PP
This design approach enables us to offer the protocol stack for the Javalanguage, Object Pascal and for C++ while maintaining similar functionality.
.PP
The C++ editions of the protocol stack have also been designed to support multiple operating system and compiler platforms, including real-time operating systems. In order to support this multi-platform approach, the C++ editions are built around a lightweight OS abstraction layer called \fIHMLIB\fP.
.PP
The Java edition is using the Java 2 Platform Standard Edition API and the Java Communications API. This enables compatibility with most VM implementations.
.PP
During the course of implementation, the usability in automation, control and other industrial environments was always kept in mind. 
