.TH "Device and Vendor Specific Functions" 3 "26 May 2004" "Modbus Protocol Library Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Device and Vendor Specific Functions \- 
.SH "Detailed Description"
.PP 
Some device specific or vendor specific functions and enhancements are supported. 
.SS "Advantec ADAM 5000/6000 Series Commands"

.in +1c
.ti -1c
.RI "int \fBMbusTcpMasterProtocol::adamSendReceiveAsciiCmd\fP (const char *const commandSz, char *responseSz)"
.br
.RI "\fISend/Receive ADAM 5000/6000 ASCII command. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int adamSendReceiveAsciiCmd (const char *const commandSz, char * responseSz)\fC [inherited]\fP"
.PP
Send/Receive ADAM 5000/6000 ASCII command. Sends an ADAM 5000/6000 ASCII command to the device and receives the reply as ASCII string. (e.g. '$01M' to retrieve the module name)
.PP
\fBParameters:\fP
.RS 4
\fIcommandSz\fP Buffer which holds command string. Must not be longer than 255 characters. 
.br
\fIresponseSz\fP Buffer which holds response string. Must be a buffer of 256 bytes. A possible trailing CR is removed.
.RE
.PP
\fBReturns:\fP
.RS 4
FTALK_SUCCESS on success or error code. See \fBProtocol Errors and Exceptions\fP for a list of error codes. 
.RE
.PP
\fBNote:\fP
.RS 4
No broadcast supported 
.RE
.PP

