.TH "Encapsulated Modbus RTU Protocol" 3 "26 May 2004" "Modbus Protocol Library Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Encapsulated Modbus RTU Protocol \- 
.SH "Detailed Description"
.PP 
The Encapsulated Modbus RTU master protocol is implemented in the class \fBMbusRtuOverTcpMasterProtocol\fP. It provides functions to establish and to close a TCP/IP connection to the slave as well as data and control functions which can be used after a connection to a slave device has been established successfully. The data and control functions are organized different conformance classes. For a more detailed description of the data and control functions see section \fBData and Control Functions for all Protocol Flavours\fP.
.PP
Using multiple instances of a \fBMbusRtuOverTcpMasterProtocol\fP class enables concurrent protocol transfers using multiple TCP/IP sessions (They should be executed in separate threads). 
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBMbusRtuOverTcpMasterProtocol\fP"
.br
.RI "\fIEncapsulated Modbus RTU Master Protocol class. \fP"
.in -1c
