.TH "notices" 3 "26 May 2004" "Modbus Protocol Library Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
notices \- Notices
\fIFieldTalk\fP was developed by:
.br
 FOCUS Software Engineering Pty Ltd, Australia.
.br
 Copyright (C) 2002-2004. All rights reserved.
.PP
FieldTalk is a trademark of FOCUS Software Engineering Pty Ltd. Modbus is a trademark or registered trademark of Schneider Automation Inc. Java and all Java-based marks are trademarks or registered trademarks of Sun Microsystems, Inc. in the U.S. and other countries. All other product and brand names mentioned in this document may be trademarks or registered trademarks of their respective owners. 
